Controllers/PaymentController.cs
using FlatworldCMS.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stripe;
using System.Threading.Tasks;
using FlatworldCMS.Models;

namespace FlatworldCMS.Controllers
{

    [MvcApplication.EmailErrorAttribute]
    public class PaymentController : Controller
    {
        UnitOfWork unitOfWork;

        // GET: Payment
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetPlans()
        {
            unitOfWork = new UnitOfWork(new Database.FlatworldCMSEntities());
            var plans = unitOfWork.Plan.GetAll().OrderBy(i => i.ID);
            return Json(plans, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdatePaymentPlan()
        {
            unitOfWork = new UnitOfWork(new Database.FlatworldCMSEntities());
            var plans = unitOfWork.Plan.GetAll().OrderBy(i => i.ID);
            return Json(plans, JsonRequestBehavior.AllowGet);
        }
        //public ActionResult Charge()
        //{

        //    return View(new StripeChargeModel());
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Charge(StripeChargeModel model)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(model);
        //    }

        //    var chargeId = await ProcessPayment(model);
        //    return View();
        //}

        //private async Task<string> ProcessPayment(StripeChargeModel model)
        //{
        //    try
        //    {
        //        return await Task.Run(() =>
        //        {
        //            var myCharge = new StripeChargeCreateOptions
        //            {
        //                // convert the amount of £12.50 to pennies i.e. 1250
        //                Amount = (int)(model.Amount * 100),
        //                Currency = "gbp",
        //                Description = "Description for test charge",

        //                SourceTokenOrExistingSourceId = model.Token
        //            };

        //            var chargeService = new StripeChargeService("sk_test_twofIRKVAAAccGD0B4TvuJbO");
        //            var stripeCharge = chargeService.Create(myCharge);

        //            return stripeCharge.Id;
        //        });
        //    }
        //    catch (Exception ex)
        //    {
        //        return null;
        //    }
        //}

        }
}

Views/Payment/Charge.cshtml
@model FlatworldCMS.Models.StripeChargeModel



<h2>Final Checkout Page</h2>

<div>
    <h4>Checkout</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            <label for="txtCardNumber">Card Number *</label>
        </dt>

        <dd>
            <input type="text" id="txtCardNumber" placeholder="Card Number e.g 1234..." />
        </dd>

        <dt>
            <label for="txtCvc">Cvc *</label>
        </dt>

        <dd>
            <input type="text" id="txtCvc" placeholder="Security Code e.g 987" />
        </dd>

        <dt>
            <label for="txtExpiryMonth">Expiry Month (MM) *</label>
        </dt>

        <dd>
            <input type="text" id="txtExpiryMonth" placeholder="01" />
        </dd>

        <dt>
            <label for="txtExpiryYear">Expiry Year (YYYY) *</label>)
        </dt>

        <dd>
            <input type="text" id="txtExpiryYear" placeholder="2015" />
        </dd>
    </dl>
</div>
@using (Html.BeginForm("Charge", "Payment", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "frmCharge" }))
{
    @Html.AntiForgeryToken()
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CardHolderName)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.CardHolderName, new { id = "txtCardHolderName" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.Amount, new { id = "txtAmount" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.AddressLine1, new { id = "txtAddress1" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.AddressLine2, new { id = "txtAddress2" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressCity)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.AddressCity, new { id = "txtCity" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressPostcode)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.AddressPostcode, new { id = "txtPostcode" })
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressCountry)
        </dt>

        <dd>
            @Html.TextBoxFor(model => model.AddressCountry, new { id = "txtCountry" })
        </dd>
    </dl>
    <p>
        @Html.HiddenFor(model => model.Token, new { id = "hdnToken" })
        @Html.ActionLink("ProcessPayment", "Charge", null, new { id = "btnCharge" })
    </p>
}
@section Scripts {
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>

    <script type="text/javascript">
        $('document').ready(function() {
            Stripe.setPublishableKey('pk_test_tkr7sjWgE0syhB6Xl7b0riRJ');

            $('#btnCharge').on('click', function(e) {
                e.preventDefault();
                e.stopPropagation();

                Stripe.card.createToken({
                    number: $('#txtCardNumber').val(),
                    cvc: $('#txtCvc').val(),
                    exp_month: $('#txtExpiryMonth').val(),
                    exp_year: $('#txtExpiryYear').val()
                }, stripeResponseHandler);
            });

            function stripeResponseHandler(status, response) {
                var $form = $('#frmCharge');

                if (response.error) {
                    // Show the errors on the form
                    alert(response.error.message);
                } else {
                    // response contains id and card, which contains additional card details
                    var token = response.id;
                    // Insert the token into the form so it gets submitted to the server
                    $('#hdnToken').val(token);
                    // and submit
                    $form.get(0).submit();
                }
            }
        });
    </script>
}